### ISSUE TITLE
🐛 `PARSE_ERROR` on type export when building inside a pnpm script on github

### ISSUE THREAD

**Issue by cruzdanilo** [privatenumber/pkgroll#92]
### Problem

the issue only happens in a very specific case:

- library builds on `prepare` (repro: https://github.com/cruzdanilo/repro-pkgroll-lib)
- library has a type-only reexport (https://github.com/cruzdanilo/repro-pkgroll-lib/blob/main/src/index.ts#L1)
- other package uses the library as a git dependency (repro: https://github.com/cruzdanilo/repro-pkgroll-ci)
- other package install dependencies **during a github action** (repro: https://github.com/cruzdanilo/repro-pkgroll-ci/actions/runs/11057662251/job/30721965511)

error:
```log
Error [RollupError]: src/Foo.ts (1:15): Expression expected (Note that you need plugins to import files that are not JavaScript)
    at Object.getRollupError (/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/shared/parseAst.js:282:41)
    ... 4 lines matching cause stack trace ...
    at async ModuleLoader.addModuleSource (/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/shared/rollup.js:20163:13) {
  cause: Error [RollupError]: Expression expected
      at Object.getRollupError (/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/shared/parseAst.js:282:41)
      at ParseError.initialise (/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/shared/rollup.js:14107:40)
      at convertNode (/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/shared/rollup.js:15717:10)
      at convertProgram (/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/shared/rollup.js:15061:12)
      at Module.setSource (/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/shared/rollup.js:16679:24)
      at async ModuleLoader.addModuleSource (/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/shared/rollup.js:20163:13) {
    code: 'PARSE_ERROR',
    pos: 15
  },
  code: 'PARSE_ERROR',
  id: '/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/src/Foo.ts',
  pos: 15,
  loc: {
    column: 15,
    file: '/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/src/Foo.ts',
    line: 1
  },
  frame: '1: export default interface Foo {}\n                  ^',
  watchFiles: [
    '/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/src/index.ts',
    '/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1799_ec9c655ee68917aa8e2862cfd73c8666/src/Foo.ts'
  ],
  [Symbol(augmented)]: true
}
```

seems like the file is being interpreted as javascript.
the error doesn't happen in multiple machines i tried (macos and linux)

### Expected behavior

no error

### Minimal reproduction URL

https://github.com/cruzdanilo/repro-pkgroll-ci/actions/runs/11057662251/job/30721965511

### Version

v2.5.0

### Node.js version

v22.9.0

### Package manager

pnpm

### Operating system

Linux

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Interesting use-case.

I'm thinking it doesn't work because pkgroll expects it to be executed when the CWD is the root of the project.

Feel free to submit a PR!

**Comment by cruzdanilo** [comment]
@privatenumber sure. i will check the actual cwd, but how would it affect ts vs js? it is also weird that it doesn't happen in other environments.

**Comment by privatenumber** [comment]
Not sure—I was just speculating since I think that's a pretty big assumption I made when I was developing it.
Please investigate and report back if you can

**Comment by cruzdanilo** [comment]
some findings:
- it runs from a temp dir, ex: `/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1899_624633c3449ae285a3524f3806c80932`
- the working dir doesn't have a `.git` dir
- github's locale is `C.UTF-8` instead of the usual `en_US.UTF-8`, which causes file sorting to be different

**Comment by nta** [comment]
This *seems* to happen as a result of the path in this scenario containing `node_modules`, leading to `rollup-plugin-dts` not emitting _any_ file and therefore returning the unprocessed input.

The order-dependent behavior here is likely due to the program cache in the plugin:

https://github.com/Swatinem/rollup-plugin-dts/blob/deddf70ccc09345f41b3129004ce3321b0529a54/src/index.ts#L45

... i.e. if a file that _imports_ the 'broken' module gets processed first, the compiler context contains an entry for the file with 'isExternalLibraryImport' set inside the TS compiler.

When testing this, if instead of reusing the object containing the `rollup-plugin-dts` instance here, I comment out the following line:

https://github.com/privatenumber/pkgroll/blob/4ae9c6756728b5b9a3377795383e4b400b29144f/src/rollup/get-rollup-configs.ts#L55

... my project (which _was_ affected by this, for it being a git module dependency as opposed to a published package) compiles fine.
